namespace NewEditor.Forms
{
    partial class FvxRandomizerForm
    {
        System.ComponentModel.IContainer components = null;
        System.Windows.Forms.Panel panelTop;
        System.Windows.Forms.Label bwGateLabel;
        System.Windows.Forms.Label labelSeed;
        System.Windows.Forms.NumericUpDown seedNumeric;
        System.Windows.Forms.Button applyButton;
        System.Windows.Forms.TabControl mainTabs;
        System.Windows.Forms.TabPage tabPagePokemonTraits;
        System.Windows.Forms.TabPage tabPageGeneShuffle;
        GeneShuffleControl geneShuffleControl;
        System.Windows.Forms.TabPage tabPageStartersStaticsTrades;
        System.Windows.Forms.TabPage tabPageMovesMovesets;
        System.Windows.Forms.TabPage tabPageFoePokemon;
        System.Windows.Forms.TabPage tabPageWildPokemon;
        System.Windows.Forms.TabPage tabPageTmHmsTutors;
        System.Windows.Forms.TabPage tabPageItems;
        System.Windows.Forms.TabPage tabPageTypes;
        System.Windows.Forms.TabPage tabPageGraphics;
        System.Windows.Forms.TabPage tabPageMiscTweaks;
        PokemonTraitsControl traitsControl;
        System.Windows.Forms.TableLayoutPanel tableSst;
        System.Windows.Forms.GroupBox groupBoxStarters;
        System.Windows.Forms.GroupBox groupBoxStatics;
        System.Windows.Forms.GroupBox groupBoxTrades;
        System.Windows.Forms.TableLayoutPanel startersInner;
        System.Windows.Forms.Panel starterColSelection;
        System.Windows.Forms.Panel starterColTypes;
        System.Windows.Forms.Panel starterColExtra;
        System.Windows.Forms.RadioButton starterModeUnchanged;
        System.Windows.Forms.RadioButton starterModeCustom;
        System.Windows.Forms.RadioButton starterModeRandomFull;
        System.Windows.Forms.RadioButton starterModeRandomBasic3;
        System.Windows.Forms.RadioButton starterModeRandomAnyBasic;
        System.Windows.Forms.ComboBox comboCustomStarter0;
        System.Windows.Forms.ComboBox comboCustomStarter1;
        System.Windows.Forms.ComboBox comboCustomStarter2;
        System.Windows.Forms.RadioButton typeRestrictNone;
        System.Windows.Forms.RadioButton typeRestrictFwg;
        System.Windows.Forms.RadioButton typeRestrictTriangle;
        System.Windows.Forms.RadioButton typeRestrictUnique;
        System.Windows.Forms.RadioButton typeRestrictSingle;
        System.Windows.Forms.ComboBox comboSingleType;
        System.Windows.Forms.CheckBox checkNoDualTypes;
        System.Windows.Forms.CheckBox checkNoLegendaries;
        System.Windows.Forms.CheckBox checkBstMin;
        System.Windows.Forms.NumericUpDown numericBstMin;
        System.Windows.Forms.CheckBox checkBstMax;
        System.Windows.Forms.NumericUpDown numericBstMax;
        System.Windows.Forms.CheckBox checkIncludeFairy;
        System.Windows.Forms.CheckBox checkStarterGraphics;
        System.Windows.Forms.TableLayoutPanel staticsInner;
        System.Windows.Forms.Panel staticColMode;
        System.Windows.Forms.Panel staticColExtra;
        System.Windows.Forms.Panel staticColLevel;
        System.Windows.Forms.RadioButton statModeUnchanged;
        System.Windows.Forms.RadioButton statModeSwap;
        System.Windows.Forms.RadioButton statModeRandomFull;
        System.Windows.Forms.RadioButton statModeSimilar;
        System.Windows.Forms.CheckBox checkStatics600;
        System.Windows.Forms.CheckBox checkStaticsLegendLimit;
        System.Windows.Forms.CheckBox checkStaticsLevelPct;
        System.Windows.Forms.TrackBar trackStaticsLevelPct;
        System.Windows.Forms.NumericUpDown numericStaticsLevelPct;
        System.Windows.Forms.TableLayoutPanel tradesInner;
        System.Windows.Forms.Panel tradeColMode;
        System.Windows.Forms.Panel tradeColDetails;
        System.Windows.Forms.RadioButton tradeModeUnchanged;
        System.Windows.Forms.RadioButton tradeModeGiven;
        System.Windows.Forms.RadioButton tradeModeBoth;
        System.Windows.Forms.CheckBox checkTradeNick;
        System.Windows.Forms.CheckBox checkTradeOt;
        System.Windows.Forms.CheckBox checkTradeIv;
        System.Windows.Forms.CheckBox checkTradeItem;
        System.Windows.Forms.Label labelPlaceholderMoves;
        System.Windows.Forms.Label labelPlaceholderFoe;
        System.Windows.Forms.Label labelPlaceholderWild;
        System.Windows.Forms.Label labelPlaceholderTmHm;
        System.Windows.Forms.Label labelPlaceholderItems;
        System.Windows.Forms.Label labelPlaceholderTypes;
        System.Windows.Forms.Label labelPlaceholderGraphics;
        System.Windows.Forms.Label labelPlaceholderMisc;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }

        void InitializeComponent()
        {
            panelTop = new System.Windows.Forms.Panel();
            bwGateLabel = new System.Windows.Forms.Label();
            labelSeed = new System.Windows.Forms.Label();
            seedNumeric = new System.Windows.Forms.NumericUpDown();
            applyButton = new System.Windows.Forms.Button();
            mainTabs = new System.Windows.Forms.TabControl();
            tabPagePokemonTraits = new System.Windows.Forms.TabPage();
            traitsControl = new PokemonTraitsControl();
            tabPageGeneShuffle = new System.Windows.Forms.TabPage();
            geneShuffleControl = new GeneShuffleControl();
            tabPageStartersStaticsTrades = new System.Windows.Forms.TabPage();
            tableSst = new System.Windows.Forms.TableLayoutPanel();
            groupBoxStarters = new System.Windows.Forms.GroupBox();
            startersInner = new System.Windows.Forms.TableLayoutPanel();
            starterColSelection = new System.Windows.Forms.Panel();
            starterModeUnchanged = new System.Windows.Forms.RadioButton();
            starterModeCustom = new System.Windows.Forms.RadioButton();
            comboCustomStarter0 = new System.Windows.Forms.ComboBox();
            comboCustomStarter1 = new System.Windows.Forms.ComboBox();
            comboCustomStarter2 = new System.Windows.Forms.ComboBox();
            starterModeRandomFull = new System.Windows.Forms.RadioButton();
            starterModeRandomBasic3 = new System.Windows.Forms.RadioButton();
            starterModeRandomAnyBasic = new System.Windows.Forms.RadioButton();
            starterColTypes = new System.Windows.Forms.Panel();
            typeRestrictNone = new System.Windows.Forms.RadioButton();
            typeRestrictFwg = new System.Windows.Forms.RadioButton();
            typeRestrictTriangle = new System.Windows.Forms.RadioButton();
            typeRestrictUnique = new System.Windows.Forms.RadioButton();
            typeRestrictSingle = new System.Windows.Forms.RadioButton();
            comboSingleType = new System.Windows.Forms.ComboBox();
            checkNoDualTypes = new System.Windows.Forms.CheckBox();
            starterColExtra = new System.Windows.Forms.Panel();
            checkNoLegendaries = new System.Windows.Forms.CheckBox();
            checkBstMin = new System.Windows.Forms.CheckBox();
            numericBstMin = new System.Windows.Forms.NumericUpDown();
            checkBstMax = new System.Windows.Forms.CheckBox();
            numericBstMax = new System.Windows.Forms.NumericUpDown();
            checkIncludeFairy = new System.Windows.Forms.CheckBox();
            checkStarterGraphics = new System.Windows.Forms.CheckBox();
            groupBoxStatics = new System.Windows.Forms.GroupBox();
            staticsInner = new System.Windows.Forms.TableLayoutPanel();
            staticColMode = new System.Windows.Forms.Panel();
            statModeUnchanged = new System.Windows.Forms.RadioButton();
            statModeSwap = new System.Windows.Forms.RadioButton();
            statModeRandomFull = new System.Windows.Forms.RadioButton();
            statModeSimilar = new System.Windows.Forms.RadioButton();
            staticColExtra = new System.Windows.Forms.Panel();
            checkStatics600 = new System.Windows.Forms.CheckBox();
            checkStaticsLegendLimit = new System.Windows.Forms.CheckBox();
            staticColLevel = new System.Windows.Forms.Panel();
            checkStaticsLevelPct = new System.Windows.Forms.CheckBox();
            trackStaticsLevelPct = new System.Windows.Forms.TrackBar();
            numericStaticsLevelPct = new System.Windows.Forms.NumericUpDown();
            groupBoxTrades = new System.Windows.Forms.GroupBox();
            tradesInner = new System.Windows.Forms.TableLayoutPanel();
            tradeColMode = new System.Windows.Forms.Panel();
            tradeModeUnchanged = new System.Windows.Forms.RadioButton();
            tradeModeGiven = new System.Windows.Forms.RadioButton();
            tradeModeBoth = new System.Windows.Forms.RadioButton();
            tradeColDetails = new System.Windows.Forms.Panel();
            checkTradeNick = new System.Windows.Forms.CheckBox();
            checkTradeOt = new System.Windows.Forms.CheckBox();
            checkTradeIv = new System.Windows.Forms.CheckBox();
            checkTradeItem = new System.Windows.Forms.CheckBox();
            tabPageMovesMovesets = new System.Windows.Forms.TabPage();
            labelPlaceholderMoves = new System.Windows.Forms.Label();
            tabPageFoePokemon = new System.Windows.Forms.TabPage();
            labelPlaceholderFoe = new System.Windows.Forms.Label();
            tabPageWildPokemon = new System.Windows.Forms.TabPage();
            labelPlaceholderWild = new System.Windows.Forms.Label();
            tabPageTmHmsTutors = new System.Windows.Forms.TabPage();
            labelPlaceholderTmHm = new System.Windows.Forms.Label();
            tabPageItems = new System.Windows.Forms.TabPage();
            labelPlaceholderItems = new System.Windows.Forms.Label();
            tabPageTypes = new System.Windows.Forms.TabPage();
            labelPlaceholderTypes = new System.Windows.Forms.Label();
            tabPageGraphics = new System.Windows.Forms.TabPage();
            labelPlaceholderGraphics = new System.Windows.Forms.Label();
            tabPageMiscTweaks = new System.Windows.Forms.TabPage();
            labelPlaceholderMisc = new System.Windows.Forms.Label();
            panelTop.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(seedNumeric)).BeginInit();
            mainTabs.SuspendLayout();
            tabPagePokemonTraits.SuspendLayout();
            tabPageGeneShuffle.SuspendLayout();
            tabPageStartersStaticsTrades.SuspendLayout();
            tableSst.SuspendLayout();
            groupBoxStarters.SuspendLayout();
            startersInner.SuspendLayout();
            starterColSelection.SuspendLayout();
            starterColTypes.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(numericBstMin)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(numericBstMax)).BeginInit();
            starterColExtra.SuspendLayout();
            groupBoxStatics.SuspendLayout();
            staticsInner.SuspendLayout();
            staticColMode.SuspendLayout();
            staticColExtra.SuspendLayout();
            staticColLevel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(trackStaticsLevelPct)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(numericStaticsLevelPct)).BeginInit();
            groupBoxTrades.SuspendLayout();
            tradesInner.SuspendLayout();
            tradeColMode.SuspendLayout();
            tradeColDetails.SuspendLayout();
            tabPageMovesMovesets.SuspendLayout();
            tabPageFoePokemon.SuspendLayout();
            tabPageWildPokemon.SuspendLayout();
            tabPageTmHmsTutors.SuspendLayout();
            tabPageItems.SuspendLayout();
            tabPageTypes.SuspendLayout();
            tabPageGraphics.SuspendLayout();
            tabPageMiscTweaks.SuspendLayout();
            SuspendLayout();

            panelTop.Dock = System.Windows.Forms.DockStyle.Top;
            panelTop.Height = 44;
            panelTop.Padding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            bwGateLabel.AutoSize = true;
            bwGateLabel.ForeColor = System.Drawing.Color.DarkRed;
            bwGateLabel.Location = new System.Drawing.Point(8, 12);
            bwGateLabel.TabIndex = 0;
            labelSeed.AutoSize = true;
            labelSeed.Text = "RNG seed (0 = random):";
            labelSeed.Location = new System.Drawing.Point(380, 12);
            labelSeed.TabIndex = 1;
            seedNumeric.Location = new System.Drawing.Point(540, 8);
            seedNumeric.Size = new System.Drawing.Size(120, 22);
            seedNumeric.Minimum = int.MinValue;
            seedNumeric.Maximum = int.MaxValue;
            seedNumeric.TabIndex = 2;
            applyButton.Text = "Apply";
            applyButton.Location = new System.Drawing.Point(680, 6);
            applyButton.Size = new System.Drawing.Size(110, 28);
            applyButton.TabIndex = 3;
            applyButton.Click += ApplyClick;
            panelTop.Controls.Add(bwGateLabel);
            panelTop.Controls.Add(labelSeed);
            panelTop.Controls.Add(seedNumeric);
            panelTop.Controls.Add(applyButton);

            mainTabs.Dock = System.Windows.Forms.DockStyle.Fill;
            mainTabs.Alignment = System.Windows.Forms.TabAlignment.Bottom;
            mainTabs.Padding = new System.Drawing.Point(12, 4);

            tabPagePokemonTraits.Text = "Pokemon Traits";
            tabPagePokemonTraits.Padding = new System.Windows.Forms.Padding(8);
            traitsControl.Dock = System.Windows.Forms.DockStyle.Fill;
            tabPagePokemonTraits.Controls.Add(traitsControl);

            tabPageGeneShuffle.Text = "Gene Shuffle";
            tabPageGeneShuffle.Padding = new System.Windows.Forms.Padding(8);
            geneShuffleControl.Dock = System.Windows.Forms.DockStyle.Fill;
            tabPageGeneShuffle.Controls.Add(geneShuffleControl);

            tabPageStartersStaticsTrades.Text = "Starters, Statics && Trades";
            tableSst.Dock = System.Windows.Forms.DockStyle.Fill;
            tableSst.ColumnCount = 3;
            tableSst.RowCount = 1;
            tableSst.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            tableSst.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            tableSst.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            tableSst.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));

            groupBoxStarters.Text = "Starter Pokemon";
            groupBoxStarters.Dock = System.Windows.Forms.DockStyle.Fill;
            groupBoxStarters.Padding = new System.Windows.Forms.Padding(6);
            startersInner.Dock = System.Windows.Forms.DockStyle.Fill;
            startersInner.ColumnCount = 3;
            startersInner.RowCount = 1;
            startersInner.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            startersInner.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            startersInner.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            startersInner.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));

            starterColSelection.Dock = System.Windows.Forms.DockStyle.Fill;
            starterModeUnchanged.AutoSize = true;
            starterModeUnchanged.Location = new System.Drawing.Point(4, 4);
            starterModeUnchanged.Text = "Unchanged";
            starterModeUnchanged.Checked = true;
            starterModeUnchanged.CheckedChanged += StarterModeChanged;
            starterModeCustom.AutoSize = true;
            starterModeCustom.Location = new System.Drawing.Point(4, 24);
            starterModeCustom.Text = "Custom";
            starterModeCustom.CheckedChanged += StarterModeChanged;
            comboCustomStarter0.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            comboCustomStarter0.Location = new System.Drawing.Point(8, 46);
            comboCustomStarter0.Size = new System.Drawing.Size(175, 24);
            comboCustomStarter0.TabIndex = 10;
            comboCustomStarter1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            comboCustomStarter1.Location = new System.Drawing.Point(8, 74);
            comboCustomStarter1.Size = new System.Drawing.Size(175, 24);
            comboCustomStarter1.TabIndex = 11;
            comboCustomStarter2.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            comboCustomStarter2.Location = new System.Drawing.Point(8, 102);
            comboCustomStarter2.Size = new System.Drawing.Size(175, 24);
            comboCustomStarter2.TabIndex = 12;
            starterModeRandomFull.AutoSize = true;
            starterModeRandomFull.Location = new System.Drawing.Point(4, 132);
            starterModeRandomFull.Text = "Random (completely)";
            starterModeRandomFull.CheckedChanged += StarterModeChanged;
            starterModeRandomBasic3.AutoSize = true;
            starterModeRandomBasic3.Location = new System.Drawing.Point(4, 154);
            starterModeRandomBasic3.Text = "Random (basic Pokemon with 2 evolutions)";
            starterModeRandomBasic3.CheckedChanged += StarterModeChanged;
            starterModeRandomAnyBasic.AutoSize = true;
            starterModeRandomAnyBasic.Location = new System.Drawing.Point(4, 176);
            starterModeRandomAnyBasic.Text = "Random (any basic Pokemon)";
            starterModeRandomAnyBasic.CheckedChanged += StarterModeChanged;
            starterColSelection.Controls.Add(starterModeUnchanged);
            starterColSelection.Controls.Add(starterModeCustom);
            starterColSelection.Controls.Add(comboCustomStarter0);
            starterColSelection.Controls.Add(comboCustomStarter1);
            starterColSelection.Controls.Add(comboCustomStarter2);
            starterColSelection.Controls.Add(starterModeRandomFull);
            starterColSelection.Controls.Add(starterModeRandomBasic3);
            starterColSelection.Controls.Add(starterModeRandomAnyBasic);

            starterColTypes.Dock = System.Windows.Forms.DockStyle.Fill;
            typeRestrictNone.AutoSize = true;
            typeRestrictNone.Location = new System.Drawing.Point(4, 4);
            typeRestrictNone.Text = "None";
            typeRestrictNone.Checked = true;
            typeRestrictNone.CheckedChanged += TypeRestrictionChanged;
            typeRestrictFwg.AutoSize = true;
            typeRestrictFwg.Location = new System.Drawing.Point(4, 24);
            typeRestrictFwg.Text = "Fire, Water, Grass";
            typeRestrictFwg.CheckedChanged += TypeRestrictionChanged;
            typeRestrictTriangle.AutoSize = true;
            typeRestrictTriangle.Location = new System.Drawing.Point(4, 44);
            typeRestrictTriangle.Text = "Any Type Triangle";
            typeRestrictTriangle.CheckedChanged += TypeRestrictionChanged;
            typeRestrictUnique.AutoSize = true;
            typeRestrictUnique.Location = new System.Drawing.Point(4, 64);
            typeRestrictUnique.Text = "Unique";
            typeRestrictUnique.CheckedChanged += TypeRestrictionChanged;
            typeRestrictSingle.AutoSize = true;
            typeRestrictSingle.Location = new System.Drawing.Point(4, 84);
            typeRestrictSingle.Text = "Single Type";
            typeRestrictSingle.CheckedChanged += TypeRestrictionChanged;
            comboSingleType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            comboSingleType.Location = new System.Drawing.Point(8, 106);
            comboSingleType.Size = new System.Drawing.Size(160, 24);
            comboSingleType.TabIndex = 20;
            comboSingleType.Enabled = false;
            checkNoDualTypes.AutoSize = true;
            checkNoDualTypes.Location = new System.Drawing.Point(4, 136);
            checkNoDualTypes.Text = "No Dual Types";
            starterColTypes.Controls.Add(typeRestrictNone);
            starterColTypes.Controls.Add(typeRestrictFwg);
            starterColTypes.Controls.Add(typeRestrictTriangle);
            starterColTypes.Controls.Add(typeRestrictUnique);
            starterColTypes.Controls.Add(typeRestrictSingle);
            starterColTypes.Controls.Add(comboSingleType);
            starterColTypes.Controls.Add(checkNoDualTypes);

            starterColExtra.Dock = System.Windows.Forms.DockStyle.Fill;
            checkNoLegendaries.AutoSize = true;
            checkNoLegendaries.Location = new System.Drawing.Point(4, 4);
            checkNoLegendaries.Text = "Don't Use Legendaries";
            checkBstMin.AutoSize = true;
            checkBstMin.Location = new System.Drawing.Point(4, 28);
            checkBstMin.Text = "Minimum";
            numericBstMin.Location = new System.Drawing.Point(88, 24);
            numericBstMin.Size = new System.Drawing.Size(56, 22);
            numericBstMin.Minimum = 1;
            numericBstMin.Maximum = 780;
            numericBstMin.Value = 307;
            checkBstMax.AutoSize = true;
            checkBstMax.Location = new System.Drawing.Point(4, 54);
            checkBstMax.Text = "Maximum";
            numericBstMax.Location = new System.Drawing.Point(88, 50);
            numericBstMax.Size = new System.Drawing.Size(56, 22);
            numericBstMax.Minimum = 1;
            numericBstMax.Maximum = 780;
            numericBstMax.Value = 320;
            checkIncludeFairy.AutoSize = true;
            checkIncludeFairy.Location = new System.Drawing.Point(4, 78);
            checkIncludeFairy.MaximumSize = new System.Drawing.Size(220, 0);
            checkIncludeFairy.Text = "Include Fairy-type (applies Fairy Vpatch when needed)";
            checkIncludeFairy.TabIndex = 31;
            checkStarterGraphics.AutoSize = true;
            checkStarterGraphics.Location = new System.Drawing.Point(4, 106);
            checkStarterGraphics.MaximumSize = new System.Drawing.Size(220, 0);
            checkStarterGraphics.Text = "Update starter graphics && cries (experimental)";
            checkStarterGraphics.TabIndex = 32;
            starterColExtra.Controls.Add(checkNoLegendaries);
            starterColExtra.Controls.Add(checkBstMin);
            starterColExtra.Controls.Add(numericBstMin);
            starterColExtra.Controls.Add(checkBstMax);
            starterColExtra.Controls.Add(numericBstMax);
            starterColExtra.Controls.Add(checkIncludeFairy);
            starterColExtra.Controls.Add(checkStarterGraphics);

            startersInner.Controls.Add(starterColSelection, 0, 0);
            startersInner.Controls.Add(starterColTypes, 1, 0);
            startersInner.Controls.Add(starterColExtra, 2, 0);
            groupBoxStarters.Controls.Add(startersInner);

            groupBoxStatics.Text = "Static Pokemon";
            groupBoxStatics.Dock = System.Windows.Forms.DockStyle.Fill;
            groupBoxStatics.Padding = new System.Windows.Forms.Padding(6);
            staticsInner.Dock = System.Windows.Forms.DockStyle.Fill;
            staticsInner.ColumnCount = 3;
            staticsInner.RowCount = 1;
            staticsInner.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            staticsInner.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            staticsInner.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            staticsInner.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));

            staticColMode.Dock = System.Windows.Forms.DockStyle.Fill;
            statModeUnchanged.AutoSize = true;
            statModeUnchanged.Location = new System.Drawing.Point(4, 4);
            statModeUnchanged.Text = "Unchanged";
            statModeUnchanged.Checked = true;
            statModeSwap.AutoSize = true;
            statModeSwap.Location = new System.Drawing.Point(4, 26);
            statModeSwap.Text = "Swap Legendaries && Swap Standards";
            statModeRandomFull.AutoSize = true;
            statModeRandomFull.Location = new System.Drawing.Point(4, 48);
            statModeRandomFull.Text = "Random (completely)";
            statModeSimilar.AutoSize = true;
            statModeSimilar.Location = new System.Drawing.Point(4, 70);
            statModeSimilar.Text = "Random (similar strength)";
            staticColMode.Controls.Add(statModeUnchanged);
            staticColMode.Controls.Add(statModeSwap);
            staticColMode.Controls.Add(statModeRandomFull);
            staticColMode.Controls.Add(statModeSimilar);

            staticColExtra.Dock = System.Windows.Forms.DockStyle.Fill;
            checkStatics600.AutoSize = true;
            checkStatics600.Location = new System.Drawing.Point(4, 4);
            checkStatics600.Text = "Randomize 600+ BST";
            checkStaticsLegendLimit.AutoSize = true;
            checkStaticsLegendLimit.Location = new System.Drawing.Point(4, 26);
            checkStaticsLegendLimit.Text = "Limit Main-Game Legendaries";
            staticColExtra.Controls.Add(checkStatics600);
            staticColExtra.Controls.Add(checkStaticsLegendLimit);

            staticColLevel.Dock = System.Windows.Forms.DockStyle.Fill;
            checkStaticsLevelPct.AutoSize = true;
            checkStaticsLevelPct.Location = new System.Drawing.Point(4, 4);
            checkStaticsLevelPct.Text = "Percentage Level Modifier";
            checkStaticsLevelPct.CheckedChanged += StaticsLevelCheckChanged;
            trackStaticsLevelPct.Location = new System.Drawing.Point(4, 28);
            trackStaticsLevelPct.Size = new System.Drawing.Size(200, 45);
            trackStaticsLevelPct.Minimum = -100;
            trackStaticsLevelPct.Maximum = 150;
            trackStaticsLevelPct.TickFrequency = 25;
            trackStaticsLevelPct.Value = 0;
            trackStaticsLevelPct.Enabled = false;
            trackStaticsLevelPct.ValueChanged += TrackStaticsLevelValueChanged;
            numericStaticsLevelPct.Location = new System.Drawing.Point(210, 30);
            numericStaticsLevelPct.Size = new System.Drawing.Size(50, 22);
            numericStaticsLevelPct.Minimum = -100;
            numericStaticsLevelPct.Maximum = 150;
            numericStaticsLevelPct.Value = 0;
            numericStaticsLevelPct.Enabled = false;
            numericStaticsLevelPct.ValueChanged += NumericStaticsLevelValueChanged;
            staticColLevel.Controls.Add(checkStaticsLevelPct);
            staticColLevel.Controls.Add(trackStaticsLevelPct);
            staticColLevel.Controls.Add(numericStaticsLevelPct);

            staticsInner.Controls.Add(staticColMode, 0, 0);
            staticsInner.Controls.Add(staticColExtra, 1, 0);
            staticsInner.Controls.Add(staticColLevel, 2, 0);
            groupBoxStatics.Controls.Add(staticsInner);

            groupBoxTrades.Text = "In-Game Trades";
            groupBoxTrades.Dock = System.Windows.Forms.DockStyle.Fill;
            groupBoxTrades.Padding = new System.Windows.Forms.Padding(6);
            tradesInner.Dock = System.Windows.Forms.DockStyle.Fill;
            tradesInner.ColumnCount = 2;
            tradesInner.RowCount = 1;
            tradesInner.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            tradesInner.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            tradesInner.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));

            tradeColMode.Dock = System.Windows.Forms.DockStyle.Fill;
            tradeModeUnchanged.AutoSize = true;
            tradeModeUnchanged.Location = new System.Drawing.Point(4, 4);
            tradeModeUnchanged.Text = "Unchanged";
            tradeModeUnchanged.Checked = true;
            tradeModeGiven.AutoSize = true;
            tradeModeGiven.Location = new System.Drawing.Point(4, 26);
            tradeModeGiven.Text = "Randomize Given Pokemon Only";
            tradeModeBoth.AutoSize = true;
            tradeModeBoth.Location = new System.Drawing.Point(4, 48);
            tradeModeBoth.Text = "Randomize Both Requested && Given Pokemon";
            tradeColMode.Controls.Add(tradeModeUnchanged);
            tradeColMode.Controls.Add(tradeModeGiven);
            tradeColMode.Controls.Add(tradeModeBoth);

            tradeColDetails.Dock = System.Windows.Forms.DockStyle.Fill;
            checkTradeNick.AutoSize = true;
            checkTradeNick.Location = new System.Drawing.Point(4, 4);
            checkTradeNick.Text = "Randomize Nicknames";
            checkTradeOt.AutoSize = true;
            checkTradeOt.Location = new System.Drawing.Point(4, 26);
            checkTradeOt.Text = "Randomize OTs";
            checkTradeIv.AutoSize = true;
            checkTradeIv.Location = new System.Drawing.Point(4, 48);
            checkTradeIv.Text = "Randomize IVs";
            checkTradeItem.AutoSize = true;
            checkTradeItem.Location = new System.Drawing.Point(4, 70);
            checkTradeItem.Text = "Randomize Items";
            tradeColDetails.Controls.Add(checkTradeNick);
            tradeColDetails.Controls.Add(checkTradeOt);
            tradeColDetails.Controls.Add(checkTradeIv);
            tradeColDetails.Controls.Add(checkTradeItem);

            tradesInner.Controls.Add(tradeColMode, 0, 0);
            tradesInner.Controls.Add(tradeColDetails, 1, 0);
            groupBoxTrades.Controls.Add(tradesInner);

            tableSst.Controls.Add(groupBoxStarters, 0, 0);
            tableSst.Controls.Add(groupBoxStatics, 1, 0);
            tableSst.Controls.Add(groupBoxTrades, 2, 0);
            tabPageStartersStaticsTrades.Controls.Add(tableSst);

            tabPageMovesMovesets.Text = "Moves && Movesets";
            labelPlaceholderMoves.Dock = System.Windows.Forms.DockStyle.Fill;
            labelPlaceholderMoves.Text = "Not implemented yet.";
            labelPlaceholderMoves.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            tabPageMovesMovesets.Controls.Add(labelPlaceholderMoves);

            tabPageFoePokemon.Text = "Foe Pokemon";
            labelPlaceholderFoe.Dock = System.Windows.Forms.DockStyle.Fill;
            labelPlaceholderFoe.Text = "Not implemented yet.";
            labelPlaceholderFoe.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            tabPageFoePokemon.Controls.Add(labelPlaceholderFoe);

            tabPageWildPokemon.Text = "Wild Pokemon";
            labelPlaceholderWild.Dock = System.Windows.Forms.DockStyle.Fill;
            labelPlaceholderWild.Text = "Not implemented yet.";
            labelPlaceholderWild.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            tabPageWildPokemon.Controls.Add(labelPlaceholderWild);

            tabPageTmHmsTutors.Text = "TM/HMs && Tutors";
            labelPlaceholderTmHm.Dock = System.Windows.Forms.DockStyle.Fill;
            labelPlaceholderTmHm.Text = "Not implemented yet.";
            labelPlaceholderTmHm.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            tabPageTmHmsTutors.Controls.Add(labelPlaceholderTmHm);

            tabPageItems.Text = "Items";
            labelPlaceholderItems.Dock = System.Windows.Forms.DockStyle.Fill;
            labelPlaceholderItems.Text = "Not implemented yet.";
            labelPlaceholderItems.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            tabPageItems.Controls.Add(labelPlaceholderItems);

            tabPageTypes.Text = "Types";
            labelPlaceholderTypes.Dock = System.Windows.Forms.DockStyle.Fill;
            labelPlaceholderTypes.Text = "Not implemented yet.";
            labelPlaceholderTypes.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            tabPageTypes.Controls.Add(labelPlaceholderTypes);

            tabPageGraphics.Text = "Graphics";
            labelPlaceholderGraphics.Dock = System.Windows.Forms.DockStyle.Fill;
            labelPlaceholderGraphics.Text = "Not implemented yet.";
            labelPlaceholderGraphics.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            tabPageGraphics.Controls.Add(labelPlaceholderGraphics);

            tabPageMiscTweaks.Text = "Misc Tweaks";
            labelPlaceholderMisc.Dock = System.Windows.Forms.DockStyle.Fill;
            labelPlaceholderMisc.Text = "Not implemented yet.";
            labelPlaceholderMisc.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            tabPageMiscTweaks.Controls.Add(labelPlaceholderMisc);

            mainTabs.TabPages.Add(tabPagePokemonTraits);
            mainTabs.TabPages.Add(tabPageGeneShuffle);
            mainTabs.TabPages.Add(tabPageStartersStaticsTrades);
            mainTabs.TabPages.Add(tabPageMovesMovesets);
            mainTabs.TabPages.Add(tabPageFoePokemon);
            mainTabs.TabPages.Add(tabPageWildPokemon);
            mainTabs.TabPages.Add(tabPageTmHmsTutors);
            mainTabs.TabPages.Add(tabPageItems);
            mainTabs.TabPages.Add(tabPageTypes);
            mainTabs.TabPages.Add(tabPageGraphics);
            mainTabs.TabPages.Add(tabPageMiscTweaks);

            AutoScaleDimensions = new System.Drawing.SizeF(7F, 16F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            ClientSize = new System.Drawing.Size(980, 620);
            Controls.Add(mainTabs);
            Controls.Add(panelTop);
            MinimumSize = new System.Drawing.Size(800, 480);
            Text = "Randomize (FVX-style)";
            Shown += FvxRandomizerForm_Shown;
            panelTop.ResumeLayout(false);
            panelTop.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(seedNumeric)).EndInit();
            mainTabs.ResumeLayout(false);
            tabPagePokemonTraits.ResumeLayout(false);
            tabPageGeneShuffle.ResumeLayout(false);
            tabPageStartersStaticsTrades.ResumeLayout(false);
            tableSst.ResumeLayout(false);
            groupBoxStarters.ResumeLayout(false);
            startersInner.ResumeLayout(false);
            starterColSelection.ResumeLayout(false);
            starterColSelection.PerformLayout();
            starterColTypes.ResumeLayout(false);
            starterColTypes.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(numericBstMin)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(numericBstMax)).EndInit();
            starterColExtra.ResumeLayout(false);
            starterColExtra.PerformLayout();
            groupBoxStatics.ResumeLayout(false);
            staticsInner.ResumeLayout(false);
            staticColMode.ResumeLayout(false);
            staticColMode.PerformLayout();
            staticColExtra.ResumeLayout(false);
            staticColExtra.PerformLayout();
            staticColLevel.ResumeLayout(false);
            staticColLevel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(trackStaticsLevelPct)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(numericStaticsLevelPct)).EndInit();
            groupBoxTrades.ResumeLayout(false);
            tradesInner.ResumeLayout(false);
            tradeColMode.ResumeLayout(false);
            tradeColMode.PerformLayout();
            tradeColDetails.ResumeLayout(false);
            tradeColDetails.PerformLayout();
            tabPageMovesMovesets.ResumeLayout(false);
            tabPageFoePokemon.ResumeLayout(false);
            tabPageWildPokemon.ResumeLayout(false);
            tabPageTmHmsTutors.ResumeLayout(false);
            tabPageItems.ResumeLayout(false);
            tabPageTypes.ResumeLayout(false);
            tabPageGraphics.ResumeLayout(false);
            tabPageMiscTweaks.ResumeLayout(false);
            ResumeLayout(false);

            mainTabs.SelectedIndex = 1;
        }
    }
}
